#!/bin/bash
# Builds dist/Tuck.app from the SwiftPM package.
# Usage: scripts/build-app.sh [debug|release]   (default: release)
set -euo pipefail
cd "$(dirname "$0")/.."

CONFIG="${1:-release}"
VERSION="$(/usr/libexec/PlistBuddy -c 'Print CFBundleShortVersionString' Packaging/Info.plist)"

echo "==> Building Tuck $VERSION ($CONFIG, arm64)"
swift build -c "$CONFIG" --arch arm64

BUILD_DIR=".build/arm64-apple-macosx/$CONFIG"
APP="dist/Tuck.app"

echo "==> Assembling $APP"
rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp "$BUILD_DIR/Tuck" "$APP/Contents/MacOS/Tuck"
cp Packaging/Info.plist "$APP/Contents/Info.plist"
printf 'APPL????' > "$APP/Contents/PkgInfo"

# App icon (generated by scripts/make-icon.sh, committed in Assets/).
if [[ -f Assets/AppIcon.icns ]]; then
  cp Assets/AppIcon.icns "$APP/Contents/Resources/AppIcon.icns"
fi

# KeyboardShortcuts ships localized resources in a .bundle that SwiftPM
# places next to the executable. It MUST be copied into Resources/ or the
# shortcut recorder UI breaks at runtime.
found_bundle=false
for bundle in "$BUILD_DIR"/*.bundle; do
  [[ -e "$bundle" ]] || continue
  cp -R "$bundle" "$APP/Contents/Resources/"
  found_bundle=true
done
if [[ "$found_bundle" != true ]]; then
  echo "warning: no resource bundles found in $BUILD_DIR" >&2
fi

# SwiftPM checkouts are read-only and cp preserves that; normalize so users
# can run `xattr -dr com.apple.quarantine` on the installed app without
# permission errors.
chmod -R u+w "$APP"

echo "==> Ad-hoc signing"
# Unsigned arm64 binaries are killed on launch, so ad-hoc signing is
# mandatory. (--deep is deprecated; the nested .bundle has no executables
# and is sealed by the outer signature.)
codesign --force --sign - "$APP"
codesign --verify --verbose=2 "$APP"

echo "==> Done: $APP"
